### ISSUE TITLE
https://github.com/01org/thermal_daemon/archive/ does not exist; therefore, cannot build rpm

### ISSUE THREAD

**Issue by davepuchyr** [01org/thermal_daemon#124]
Should the url point somewhere on https://download.01.org/?

**Comment by ArchangeGabriel** [comment]
Nope. The top directory does not exist, but files inside do:
https://github.com/01org/thermal_daemon/archive/v1.6.tar.gz

Nothing related to thermald is released under 01.org. See second part of this answer: https://github.com/01org/thermal_daemon/issues/108#issuecomment-271609671.

**Comment by davepuchyr** [comment]
Your are right.  The problem is in thermal-daemon.spec.  Source0 should be `https://github.com/01org/thermal_daemon/archive/%{version}.tar.gz`, not 
`https://github.com/01org/thermal_daemon/archive/v%{version}.tar.gz`.  (Note the "v" after archive/ in the incorrect version.)
