### ISSUE TITLE
Makefile hardcodes -fopenmp, but no OpenMP directives or functions seem to be used

### ISSUE THREAD

**Issue by ravenexp** [01org/thermal_daemon#129]
This may introduce an unnecessary dependency.
GCC requires libgomp to compile OpenMP programs, for example.

**Comment by spandruvada** [comment]
On Fri, 2017-06-02 at 00:40 -0700, Sergey Kvachonok wrote:
> This may introduce an unnecessary dependency.
> GCC requires libgomp to compile OpenMP programs, for example.
Thanks for finding. OpenMP was used before but later removed. But the
flag remained.

**Comment by ravenexp** [comment]
Resolved by 90169f80a70efd4d5b6101e87666cd355dbd786f

Thank you!
