### ISSUE TITLE
Makefile hardcodes -fpermissive unnecessarily

### ISSUE THREAD

**Issue by ravenexp** [01org/thermal_daemon#130]
-fpermissive hides bugs and should never be used with maintained code.

The current code builds just fine without -fpermissive.

**Comment by spandruvada** [comment]
On Fri, 2017-06-02 at 01:39 -0700, Sergey Kvachonok wrote:
> -fpermissive hides bugs and should never be used with maintained
> code.
We can remove this flag.

**Comment by ravenexp** [comment]
Resolved by 90169f80a70efd4d5b6101e87666cd355dbd786f

Thank you!
