### ISSUE TITLE
thermald stall my system (linux 3.18)

### ISSUE THREAD

**Issue by tomasbortoli** [01org/thermal_daemon#51]
Hi people! I've done "some" tests and I got that running thermald in a linux system with kernel 3.18 (also with the 3.14) creates problems, at least at me. When the temperature go high and thermald has to intervene, the system totally lock. I think it's a kernel crash but I really don't know. 
If I disable thermald the system halts instantly thanks to the hardware lifesaving mechanism.
If I use the kernel version 3.12 everything goes well and no strange crashes happened.

Anyone have an idea of why this happen and if this is caused by a kernel bug?

In addition, I use thermald in daemon mode with no additional parameters.

Here is the output of uname -a:
Linux kali 3.18.0-kali1-amd64 #1 SMP Debian 3.18.3-1~kali4 (2015-01-22) x86_64 GNU/Linux

Thanks in advance!!

**Comment by spandruvada** [comment]
On Sun, 2015-03-01 at 14:00 -0800, tomasbortoli wrote:
> Hi people! I've done "some" tests and I got that running thermald in a
> linux system with kernel 3.18 (also with the 3.14) creates problems,
> at least at me. When the temperature go high and thermald has to
> intervene, the system totally lock. I think it's a kernel crash but I
> really don't know. 
3.18 kernel had issue, which I think was addressed by a stable release
update.
I see you closed this issue. Is this fixed?

Thanks,
Srinivas

**Comment by tomasbortoli** [comment]
Yeah the problem magically disappear.. I used the 3.12 for a few days and when I decided to make a report to the kernel's developers the problem is no longer appeared.

Thanks anyway

Date: Mon, 2 Mar 2015 08:32:41 -0800
