### ISSUE TITLE
thermald aggressive configuration to prevent shutdown

### ISSUE THREAD

**Issue by tomasbortoli** [01org/thermal_daemon#54]
Hi! I've a sony vaio laptop with lost of overheating problem. On my linux system when I try to run eclipse luna I got shutdown by overheating. Thermald does not handle my situation with the standard configuration.
I've read the manual page on thermal-conf.xml but without results. Does someone have an idea on how to create an aggressive behavior that shrink down the cpu freq when a certain temp is reached? How could I do this??

Thanks very much!

**Comment by spandruvada** [comment]
On Wed, 2015-04-22 at 05:57 -0700, tomasbortoli wrote:
> Hi! I've a sony vaio laptop with lost of overheating problem. On my
> linux system when I try to run eclipse luna I got shutdown by
> overheating. Thermald does not handle my situation with the standard
> configuration.
> I've read the manual page on thermal-conf.xml but without results.
> Does someone have an idea on how to create an aggressive behavior that
> shrink down the cpu freq when a certain temp is reached? How could I
> do this??
> 
> Thanks very much! 
> 
Looks like you close the bug. Is it fixed?
