### ISSUE TITLE
Got errors compiling thermald

### ISSUE THREAD

**Issue by tomasbortoli** [01org/thermal_daemon#58]
Hi all, I don't know why but I got this error when trying to compile with make thermald.

here's my out of uname -a:
Linux localhost 3.14-kali1-amd64 #1 SMP Debian 3.14.5-1kali1 (2014-06-07) x86_64 GNU/Linux

All the needed packets for the compilation are installed and the config doesn't seems to create problems.

When I try to  compile I get:
...
src/thd_trt_art_reader.cpp: In function ‘void associate_device(sub_type_t, std::string&)’:
src/thd_trt_art_reader.cpp:62:2: error: ‘DIR’ was not declared in this scope
src/thd_trt_art_reader.cpp:62:7: error: ‘dir’ was not declared in this scope
src/thd_trt_art_reader.cpp:66:38: error: ‘opendir’ was not declared in this scope
...

I've looked for DIR and seems that isn't really declared anywhere..
Am I wrong on something?

Anyone can help me??

Thanks in advance

**Comment by spandruvada** [comment]
On Sun, 2015-05-10 at 15:03 -0700, tomasbortoli wrote:
> Hi all, I don't know why but I got this error when trying to compile
> with make thermald.
> 
> here's my out of uname -a:
> Linux localhost 3.14-kali1-amd64 #1 SMP Debian 3.14.5-1kali1
> (2014-06-07) x86_64 GNU/Linux
> 
> All the needed packets for the compilation are installed and the
> config doesn't seems to create problems.
> 
> When I try to compile I get:
> ...
> src/thd_trt_art_reader.cpp: In function ‘void
> associate_device(sub_type_t, std::string&)’:
> src/thd_trt_art_reader.cpp:62:2: error: ‘DIR’ was not declared in this
> scope
> src/thd_trt_art_reader.cpp:62:7: error: ‘dir’ was not declared in this
> scope
> src/thd_trt_art_reader.cpp:66:38: error: ‘opendir’ was not declared in
> this scope
> ...
> 
> I've looked for DIR and seems that isn't really declared anywhere..
> Am I wrong on something?
> 
Can you add to src/thd_trt_art_reader.cpp
#include <dirent.h>

**Comment by tomasbortoli** [comment]
That works. Thank you very much! But why this embarassment?
