### ISSUE TITLE
Handling of no_turbo

### ISSUE THREAD

**Issue by pyamsoft** [01org/thermal_daemon#59]
To my understanding, writing a "1" to the no_turbo file in the intel_pstate sys directory will prevent the CPU from entering turbo frequencies. When a "1" is manually written to the no_turbo file, and then thermald is ran using the systemd service, thermald overwrites the manual assignment and enables turbo, writing a "0" as the value of no_turbo. Is there a way to prevent thermald from overriding manual assignment of the no_turbo value?

Arch Linux 64 bit
Using the thermald package from the AUR modified to use the recently released thermald 1.4

**Comment by spandruvada** [comment]
On Mon, 2015-05-18 at 13:16 -0700, pyamsoft wrote:
> To my understanding, writing a "1" to the no_turbo file in the
> intel_pstate sys directory will prevent the CPU from entering turbo
> frequencies. When a "1" is manually written to the no_turbo file, and
> then thermald is ran using the systemd service, thermald overwrites
> the manual assignment and enables turbo, writing a "0" as the value of
> no_turbo. Is there a way to prevent thermald from overriding manual
> assignment of the no_turbo value?

Good question. It will be a good enhancement. Currently thermald will
own the field.
You can remove Intel P state usage from thermald by removing "Intel P
state" line from
thermal-cpu-cdev-order.xml, search for this file from root

**Comment by pyamsoft** [comment]
I would not know though how thermald would be able to differentiate between writes to no_turbo that were manually made by a user, and writes made by a program or daemon like thermald. Perhaps it would be best that thermald owns the no_turbo field.

But thank you for your advice about the cdev-order file, I will see if it has the effect that I desire.

**Comment by pyamsoft** [comment]
Would there be a way to add a no_turbo like option to the thermal-conf.xml? This would be helpful for users who want thermald to manage the frequencies of the intel_pstate driver but not use turbo frequencies at all.
