### ISSUE TITLE
Cannot understand configuration file

### ISSUE THREAD

**Issue by diegogarciaa** [01org/thermal_daemon#76]
I cannot understand how to configure my fan control using thermald configuration file. Please, could you help me?

I have a dell latitude 3450 i5 5200u processor
Update2* I am using ubuntu 15.10 with all upgraded.

sensors output:

acpitz-virtual-0
Adapter: Virtual device
temp1:        +25.0°C  (crit = +107.0°C)
temp2:        +27.8°C  (crit = +100.0°C)
temp3:        +29.8°C  (crit = +100.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Physical id 0:  +44.0°C  (high = +105.0°C, crit = +105.0°C)
Core 0:         +44.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:         +44.0°C  (high = +105.0°C, crit = +105.0°C)

dell_smm-virtual-0
Adapter: Virtual device
Processor Fan: 2895 RPM
CPU:            +43.0°C  
Other:          +42.0°C  
Ambient:        +46.0°C  
SODIMM:         +41.0°C  

Others output:

find /sys/class/hwmon/* -exec echo -n "{}: " \; -exec cat {}/name \; 

/sys/class/hwmon/hwmon0: acpitz
/sys/class/hwmon/hwmon1: coretemp
/sys/class/hwmon/hwmon2: dell_smm

hwmon2 ls output:

ls /sys/class/hwmon/hwmon2/
fan1_input  power      temp1_input  temp2_label  temp4_input
fan1_label  pwm1       temp1_label  temp3_input  temp4_label
name        subsystem  temp2_input  temp3_label  uevent

Here is my thermald configuration file:

http://pastebin.com/3MG6digN

I would like to know how to use intel pstate and fan control to keep the laptop a little hotter, but the fan speed a lot less. In windows 10 I can set the battery save mode and the fan wont turn on. I would like to have the same behavior in linux, but I cannot understand how to use the configuration file.

Update: I was reading on another post that thermald uses /sys/class/thermal for the cooling devices https://github.com/01org/thermal_daemon/issues/62

ls /sys/class/thermal/
cooling_device0  cooling_device4  cooling_device8  thermal_zone2
cooling_device1  cooling_device5  cooling_device9  thermal_zone3
cooling_device2  cooling_device6  thermal_zone0
cooling_device3  cooling_device7  thermal_zone1

Seems something went wrong...despite having inumerous devices, thermald did not configured anyone

cat /sys/class/thermal/cooling_device*/type
Fan
Fan
Fan
Fan
Fan
Processor
Processor
Processor
Processor
intel_powerclamp

Thanks.

**Comment by spandruvada** [comment]
On Sun, 2015-11-22 at 11:20 -0800, diegogarciaa wrote:
> I cannot understand how to configure my fan control using thermald
> configuration file. Please, could you help me?
Please look here:
https://github.com/01org/thermal_daemon/issues/30

Thanks,
Srinivas

**Comment by diegogarciaa** [comment]
I was reading that yesterday before giving up... I cry now.. joking..

I will try again. Thanks for fast response.

**Comment by spandruvada** [comment]
On Mon, 2015-11-23 at 10:14 -0800, diegogarciaa wrote:
> I was reading that yesterday before giving up... I cry now.. joking..
> I will try again. Thanks for fast response.
First try from command line, whether you can control FAN on your
machine. You need a kob to control. Then only you can configure
thermald.

**Comment by diegogarciaa** [comment]
Man, let's be honest, you need to rewrite that configuration file... no way sane people can use that. Cant you see? I have been reading the link you sent me over 3 days, I cannot understand yet.

I mean, the correct way of thermald working is not zero configuration... that is stupid... zero configuration?

**Comment by diegogarciaa** [comment]
I gave up...I just capped my temperature at 52000 (52º celsius)
