### ISSUE TITLE
Thermald crashes early on after read_trip_points

### ISSUE THREAD

**Issue by sbougerel** [01org/thermal_daemon#80]
Using Dell XPS 9350, on Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz, with Archlinux testing:

```
# uname -a
Linux eva 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux
```

Thermald (release 1.4.3) crashes immediately after startup:

```
# thermald --no-daemon --loglevel=debug
RAPL sysfs present 
RAPL base path /sys/class/powercap/intel-rapl/
RAPL domain dir power
 /sys/class/powercap/intel-rapl/power/name doesn't exist
RAPL domain dir enabled
 /sys/class/powercap/intel-rapl/enabled/name doesn't exist
RAPL domain dir intel-rapl:0
name package-0
RAPL base path /sys/class/powercap/intel-rapl/intel-rapl:0/
RAPL domain dir name
 /sys/class/powercap/intel-rapl/intel-rapl:0/name/name doesn't exist
RAPL domain dir power
 /sys/class/powercap/intel-rapl/intel-rapl:0/power/name doesn't exist
RAPL domain dir constraint_0_time_window_us
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_time_window_us/name doesn't exist
RAPL domain dir constraint_1_power_limit_uw
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_1_power_limit_uw/name doesn't exist
RAPL domain dir enabled
 /sys/class/powercap/intel-rapl/intel-rapl:0/enabled/name doesn't exist
RAPL domain dir device
 /sys/class/powercap/intel-rapl/intel-rapl:0/device/name doesn't exist
RAPL domain dir constraint_0_power_limit_uw
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_power_limit_uw/name doesn't exist
RAPL domain dir subsystem
 /sys/class/powercap/intel-rapl/intel-rapl:0/subsystem/name doesn't exist
RAPL domain dir constraint_0_name
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_name/name doesn't exist
RAPL domain dir constraint_1_name
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_1_name/name doesn't exist
RAPL domain dir energy_uj
 /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj/name doesn't exist
RAPL domain dir constraint_1_max_power_uw
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_1_max_power_uw/name doesn't exist
RAPL domain dir uevent
 /sys/class/powercap/intel-rapl/intel-rapl:0/uevent/name doesn't exist
RAPL domain dir max_energy_range_uj
 /sys/class/powercap/intel-rapl/intel-rapl:0/max_energy_range_uj/name doesn't exist
RAPL domain dir constraint_0_max_power_uw
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_max_power_uw/name doesn't exist
RAPL domain dir constraint_1_time_window_us
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_1_time_window_us/name doesn't exist
RAPL domain dir intel-rapl:0:0
name core
RAPL domain dir intel-rapl:0:1
name uncore
RAPL domain dir intel-rapl:0:2
name dram
RAPL domain count 1
RAPL domain dir subsystem
 /sys/class/powercap/intel-rapl/subsystem/name doesn't exist
RAPL domain dir uevent
 /sys/class/powercap/intel-rapl/uevent/name doesn't exist
RAPL domain count 1
22 CPUID levels; family:model:stepping 0x6:4e:3 (6:78:3)
 Need Linux PowerCap sysfs 
Running on a vanilla kernel
Polling mode is enabled: 4
thd_read_default_thermal_sensors 
sensor_update: type INT3400
sensor_update: type B0D4
sensor_update: type GEN1
sensor_update: type SEN1
sensor_update: type SEN2
sensor_update: type acpitz
sensor_update: type x86_pkg_temp
thd_read_default_thermal_sensors loaded 7 sensors 
dts /sys/devices/platform/coretemp.0/name doesn't exist
 File Exists: file_name /usr/var/run/thermald/thermal-conf.xml.auto, so no regenerate
Using generated /usr/var/run/thermald/thermal-conf.xml.auto
 Dumping parsed XML Data
 *** Index 0 ***
Name: _TRTexport
UUID: 
type: 0
	Zone 0 
	 Name: cpu
		 Trip Point 0 
		  temp 0 
		  trip type 2 
		  hyst id 0 
		  sensor type hwmon 
		  cdev index 0 
			  type rapl_controller 
			  influence 10 
			  SamplingPeriod 5 
		  cdev index 1 
			  type rapl_controller_dram 
			  influence 3 
			  SamplingPeriod 10 
	Zone 1 
	 Name: TMEM
		 Trip Point 0 
		  temp 0 
		  trip type 2 
		  hyst id 0 
		  sensor type TMEM 
		  cdev index 0 
			  type rapl_controller 
			  influence 8 
			  SamplingPeriod 60 
		  cdev index 1 
			  type rapl_controller_dram 
			  influence 6 
			  SamplingPeriod 30 
	Zone 2 
	 Name: SEN1
		 Trip Point 0 
		  temp 0 
		  trip type 2 
		  hyst id 0 
		  sensor type SEN1 
		  cdev index 0 
			  type rapl_controller 
			  influence 9 
			  SamplingPeriod 30 
	Zone 3 
	 Name: GEN1
		 Trip Point 0 
		  temp 0 
		  trip type 2 
		  hyst id 0 
		  sensor type GEN1 
		  cdev index 0 
			  type rapl_controller 
			  influence 3 
			  SamplingPeriod 60 
	Zone 4 
	 Name: SEN2
		 Trip Point 0 
		  temp 0 
		  trip type 2 
		  hyst id 0 
		  sensor type SEN2 
		  cdev index 0 
			  type rapl_controller 
			  influence 6 
			  SamplingPeriod 30 
		  cdev index 1 
			  type rapl_controller_dram 
			  influence 4 
			  SamplingPeriod 30 
config product name [XPS139350] match with [XPS139350]
Product Name matched 
sensor index:0 INT3400 /sys/class/thermal/thermal_zone0/ Async:0 
sensor index:1 B0D4 /sys/class/thermal/thermal_zone1/ Async:0 
sensor index:2 GEN1 /sys/class/thermal/thermal_zone2/ Async:0 
sensor index:3 SEN1 /sys/class/thermal/thermal_zone3/ Async:0 
sensor index:4 SEN2 /sys/class/thermal/thermal_zone4/ Async:0 
sensor index:5 acpitz /sys/class/thermal/thermal_zone5/ Async:1 
sensor index:6 x86_pkg_temp /sys/class/thermal/thermal_zone6/ Async:1 
sensor index:7 hwmon /sys/class/hwmon/hwmon1/temp1_input Async:0 
sensor index:8 hwmon /sys/class/hwmon/hwmon1/temp2_input Async:0 
sensor index:9 hwmon /sys/class/hwmon/hwmon1/temp3_input Async:0 
thd_read_default_cooling devices 
cooling dev 0:0:3:Processor
cooling dev 1:0:3:Processor
cooling dev 2:0:3:Processor
cooling dev 3:0:3:Processor
cooling dev 4:-1:50:intel_powerclamp
thd_read_default_cooling devices loaded 5 cdevs 
ppcc limits max:35000000 min:35000000  min_win:28000000 step:1000000
RAPL max limit 0 increment: 1000000
set_pid_param 5 [1000.100,10]
Use Default pstate drv settings
cooling dev index:6, curr_state:0, max_state:10, unit:10.000000, min_com:0, type:intel_pstate
config product name [XPS139350] match with [XPS139350]
Product Name matched 
pstate CPU present 0-3
name = package-0
name = core
name = uncore
name = dram
sysfs read failed constraint_0_max_power_uw
powercap RAPL invalid max power limit range 
Calculate dynamically phy_max 
0: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0 
1: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0 
2: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0 
3: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0 
4: intel_powerclamp, C:-1 MN: 0 MX:50 ST:5 pt:/sys/class/thermal/ rd_bk 0 
5: rapl_controller, C:0 MN: 0 MX:0 ST:1000000 pt:/sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/ rd_bk 1 
6: intel_pstate, C:0 MN: 0 MX:10 ST:1 pt:/sys/devices/system/cpu/intel_pstate/ rd_bk 1 
7: rapl_controller_dram, C:0 MN: 0 MX:500000 ST:500000 pt:/sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/intel-rapl:0:2/ rd_bk 1 
8: LCD, C:0 MN: 0 MX:937 ST:93 pt:/sys/class/backlight/intel_backlight/ rd_bk 1 
thd_read_default_thermal_zones 
Added zone index:0 
Thermal Zone look for 0/type
Thermal Zone 0:INT3400
read_trip_points Added 0 trips 
Added zone index:1 
Thermal Zone look for 1/type
Thermal Zone 1:B0D4
read_trip_points 1/trip_point_0_type:critical 
read_trip_points 1/trip_point_0_temp:115000 
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_filebuf::underflow error reading the file
[1]    5789 abort      sudo thermald --no-daemon --loglevel=debug
```

**Comment by spandruvada** [comment]
On Thu, 2016-02-11 at 19:32 -0800, sbougerel wrote:

Using Dell XPS 9350, on Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz, with Archlinux testing:

# uname -a
Linux eva 4.4.1-2-ARCH #1 SMP PREEMPT Wed Feb 3 13:12:33 UTC 2016 x86_64 GNU/Linux


Thermald (release 1.4.3) crashes immediately after startup:

This commit should have fixed this. If you are using ubuntu package, they already included this.
https://github.com/01org/thermal_daemon/commit/ba4fe1e7bb77d09530544cda860fba559603ec83

Thanks,
Srinivas


# thermald --no-daemon --loglevel=debug
RAPL sysfs present
RAPL base path /sys/class/powercap/intel-rapl/
RAPL domain dir power
 /sys/class/powercap/intel-rapl/power/name doesn't exist
RAPL domain dir enabled
 /sys/class/powercap/intel-rapl/enabled/name doesn't exist
RAPL domain dir intel-rapl:0
name package-0
RAPL base path /sys/class/powercap/intel-rapl/intel-rapl:0/
RAPL domain dir name
 /sys/class/powercap/intel-rapl/intel-rapl:0/name/name doesn't exist
RAPL domain dir power
 /sys/class/powercap/intel-rapl/intel-rapl:0/power/name doesn't exist
RAPL domain dir constraint_0_time_window_us
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_time_window_us/name doesn't exist
RAPL domain dir constraint_1_power_limit_uw
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_1_power_limit_uw/name doesn't exist
RAPL domain dir enabled
 /sys/class/powercap/intel-rapl/intel-rapl:0/enabled/name doesn't exist
RAPL domain dir device
 /sys/class/powercap/intel-rapl/intel-rapl:0/device/name doesn't exist
RAPL domain dir constraint_0_power_limit_uw
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_power_limit_uw/name doesn't exist
RAPL domain dir subsystem
 /sys/class/powercap/intel-rapl/intel-rapl:0/subsystem/name doesn't exist
RAPL domain dir constraint_0_name
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_name/name doesn't exist
RAPL domain dir constraint_1_name
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_1_name/name doesn't exist
RAPL domain dir energy_uj
 /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj/name doesn't exist
RAPL domain dir constraint_1_max_power_uw
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_1_max_power_uw/name doesn't exist
RAPL domain dir uevent
 /sys/class/powercap/intel-rapl/intel-rapl:0/uevent/name doesn't exist
RAPL domain dir max_energy_range_uj
 /sys/class/powercap/intel-rapl/intel-rapl:0/max_energy_range_uj/name doesn't exist
RAPL domain dir constraint_0_max_power_uw
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_0_max_power_uw/name doesn't exist
RAPL domain dir constraint_1_time_window_us
 /sys/class/powercap/intel-rapl/intel-rapl:0/constraint_1_time_window_us/name doesn't exist
RAPL domain dir intel-rapl:0:0
name core
RAPL domain dir intel-rapl:0:1
name uncore
RAPL domain dir intel-rapl:0:2
name dram
RAPL domain count 1
RAPL domain dir subsystem
 /sys/class/powercap/intel-rapl/subsystem/name doesn't exist
RAPL domain dir uevent
 /sys/class/powercap/intel-rapl/uevent/name doesn't exist
RAPL domain count 1
22 CPUID levels; family:model:stepping 0x6:4e:3 (6:78:3)
 Need Linux PowerCap sysfs
Running on a vanilla kernel
Polling mode is enabled: 4
thd_read_default_thermal_sensors
sensor_update: type INT3400
sensor_update: type B0D4
sensor_update: type GEN1
sensor_update: type SEN1
sensor_update: type SEN2
sensor_update: type acpitz
sensor_update: type x86_pkg_temp
thd_read_default_thermal_sensors loaded 7 sensors
dts /sys/devices/platform/coretemp.0/name doesn't exist
 File Exists: file_name /usr/var/run/thermald/thermal-conf.xml.auto, so no regenerate
Using generated /usr/var/run/thermald/thermal-conf.xml.auto
 Dumping parsed XML Data
 *** Index 0 ***
Name: _TRTexport
UUID:
type: 0
    Zone 0
     Name: cpu
         Trip Point 0
          temp 0
          trip type 2
          hyst id 0
          sensor type hwmon
          cdev index 0
              type rapl_controller
              influence 10
              SamplingPeriod 5
          cdev index 1
              type rapl_controller_dram
              influence 3
              SamplingPeriod 10
    Zone 1
     Name: TMEM
         Trip Point 0
          temp 0
          trip type 2
          hyst id 0
          sensor type TMEM
          cdev index 0
              type rapl_controller
              influence 8
              SamplingPeriod 60
          cdev index 1
              type rapl_controller_dram
              influence 6
              SamplingPeriod 30
    Zone 2
     Name: SEN1
         Trip Point 0
          temp 0
          trip type 2
          hyst id 0
          sensor type SEN1
          cdev index 0
              type rapl_controller
              influence 9
              SamplingPeriod 30
    Zone 3
     Name: GEN1
         Trip Point 0
          temp 0
          trip type 2
          hyst id 0
          sensor type GEN1
          cdev index 0
              type rapl_controller
              influence 3
              SamplingPeriod 60
    Zone 4
     Name: SEN2
         Trip Point 0
          temp 0
          trip type 2
          hyst id 0
          sensor type SEN2
          cdev index 0
              type rapl_controller
              influence 6
              SamplingPeriod 30
          cdev index 1
              type rapl_controller_dram
              influence 4
              SamplingPeriod 30
config product name [XPS139350] match with [XPS139350]
Product Name matched
sensor index:0 INT3400 /sys/class/thermal/thermal_zone0/ Async:0
sensor index:1 B0D4 /sys/class/thermal/thermal_zone1/ Async:0
sensor index:2 GEN1 /sys/class/thermal/thermal_zone2/ Async:0
sensor index:3 SEN1 /sys/class/thermal/thermal_zone3/ Async:0
sensor index:4 SEN2 /sys/class/thermal/thermal_zone4/ Async:0
sensor index:5 acpitz /sys/class/thermal/thermal_zone5/ Async:1
sensor index:6 x86_pkg_temp /sys/class/thermal/thermal_zone6/ Async:1
sensor index:7 hwmon /sys/class/hwmon/hwmon1/temp1_input Async:0
sensor index:8 hwmon /sys/class/hwmon/hwmon1/temp2_input Async:0
sensor index:9 hwmon /sys/class/hwmon/hwmon1/temp3_input Async:0
thd_read_default_cooling devices
cooling dev 0:0:3:Processor
cooling dev 1:0:3:Processor
cooling dev 2:0:3:Processor
cooling dev 3:0:3:Processor
cooling dev 4:-1:50:intel_powerclamp
thd_read_default_cooling devices loaded 5 cdevs
ppcc limits max:35000000 min:35000000  min_win:28000000 step:1000000
RAPL max limit 0 increment: 1000000
set_pid_param 5 [1000.100,10]
Use Default pstate drv settings
cooling dev index:6, curr_state:0, max_state:10, unit:10.000000, min_com:0, type:intel_pstate
config product name [XPS139350] match with [XPS139350]
Product Name matched
pstate CPU present 0-3
name = package-0
name = core
name = uncore
name = dram
sysfs read failed constraint_0_max_power_uw
powercap RAPL invalid max power limit range
Calculate dynamically phy_max
0: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0
1: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0
2: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0
3: Processor, C:0 MN: 0 MX:3 ST:1 pt:/sys/class/thermal/ rd_bk 0
4: intel_powerclamp, C:-1 MN: 0 MX:50 ST:5 pt:/sys/class/thermal/ rd_bk 0
5: rapl_controller, C:0 MN: 0 MX:0 ST:1000000 pt:/sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/ rd_bk 1
6: intel_pstate, C:0 MN: 0 MX:10 ST:1 pt:/sys/devices/system/cpu/intel_pstate/ rd_bk 1
7: rapl_controller_dram, C:0 MN: 0 MX:500000 ST:500000 pt:/sys/devices/virtual/powercap/intel-rapl/intel-rapl:0/intel-rapl:0:2/ rd_bk 1
8: LCD, C:0 MN: 0 MX:937 ST:93 pt:/sys/class/backlight/intel_backlight/ rd_bk 1
thd_read_default_thermal_zones
Added zone index:0
Thermal Zone look for 0/type
Thermal Zone 0:INT3400
read_trip_points Added 0 trips
Added zone index:1
Thermal Zone look for 1/type
Thermal Zone 1:B0D4
read_trip_points 1/trip_point_0_type:critical
read_trip_points 1/trip_point_0_temp:115000
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_filebuf::underflow error reading the file
[1]    5789 abort      sudo thermald --no-daemon --loglevel=debug

**Comment by sbougerel** [comment]
Hi Srinivas, 

Thanks for your prompt reply. The Archlinux package has been updated to the latest release with your commit. I can confirm that it fixes the crash that I reported.

This isssue is fixed, has far as I am concerned.

Regards, 
Sylvain

**Comment by spandruvada** [comment]
On Thu, 2016-02-18 at 23:29 -0800, sbougerel wrote:
> Hi Srinivas,
Hi Sylvain,

Can you regenerate package? There was some security issue.

Thanks,
Srinivas

**Comment by ArchangeGabriel** [comment]
I’m the current maintainer of the package for ArchLinux. ;) Just updated it.
