### ISSUE TITLE
Question: logic check needed on thermald-conf.xml

### ISSUE THREAD

**Issue by glitsj16** [01org/thermal_daemon#93]
Hi, I'm trying to configure thermald on an older Intel Core2 Duo laptop (currently running linux kernel 4.6.3). As this CPU does not support Intel RAPL or Intel Powerclamp I had to write a custom thermald-conf.xml. I wonder whether someone more knowledgeable could have a look at the xml config and advise on what could be improved. Thermald does start, yet I have a lot of 'csys_fs::read exception' messages in systemd's status output.

Here's my thermald config and some relevant output:
https://gist.github.com/dd32a00d1446647c2c716da6a1d1191c

If any additional info is needed, I'll be happy to oblige, regards.

**Comment by spandruvada** [comment]
On Thu, 2016-06-30 at 03:42 -0700, glitsj16 wrote:
> Hi, I'm trying to configure thermald on an older Intel Core2 Duo
> laptop (currently running linux kernel 4.6.3). As this CPU does not
> support Intel RAPL or Intel Powerclamp I had to write a custom
> thermald-conf.xml. I wonder whether someone more knowledgeable could
> have a look at the xml config and advise on what could be improved.
> Thermald does start, yet I have a lot of 'csys_fs::read exception'
> messages in systemd's status output.
> Here's my thermald config and some relevant output:
> https://gist.github.com/dd32a00d1446647c2c716da6a1d1191c
> If any additional info is needed, I'll be happy to oblige, regards.
Every path you specify in the configuration, you should be able to read
from a command line in a terminal. For example, this path is just a
directory, so need to add temp
/sys/class/thermal/thermal_zone0/

Try
# cat /sys/class/thermal/thermal_zone0/temp
# cat /sys/class/thermal/thermal_zone1/temp

If they work then change then add to config file.

You also need to decide if you want to control your temperature with or
without FAN. I see you have a FAN as a cooling device, first try from a
command line whether FAN control works.

Try something like this:
#cd /sys/class/thermal/cooling_device3
#echo 0 > cur_state
It should stop the Fan
#echo 1 > cur_state
It should start the Fan

run the thermald with loglevel=debug to see which read is causing
exception. 

Thanks,
Srinivas

**Comment by glitsj16** [comment]
That was very helpfull advise, thank you. Adding /sys/class/thermal/thermal_zone0/temp (& similar for tz1) looks like having fixed all the previous csys_fs::read exception errors. Fan controls do work. So I have only one question left. You mention I have to decide on controlling temperature with or without fan. Do I remove the <CoolingDevice> section for fans entirely if I wanted to let Processor control temp? Or is this configured via the <influence> entrees?

Regards!

**Comment by spandruvada** [comment]
On Thu, 2016-06-30 at 12:05 -0700, glitsj16 wrote:
> That was very helpfull advise, thank you. Adding
> /sys/class/thermal/thermal_zone0/temp (& similar for tz1) looks like
> having fixed all the previous csys_fs::read exception errors. Fan
> controls do work. So I have only one question left. You mention I
> have to decide on controlling temperature with or without fan. Do I
> remove the section for fans entirely if I wanted to let Processor
> control temp? Or is this configured via the entrees?
This is user preference. Some user wants Fan to be ON at lower
temperature so that they get higher performance without processor
getting throttled.
You can have one trip at
50000 to turn on FAN
and 85000 to turn on processor throttling.

Thanks,
Srinivas

**Comment by glitsj16** [comment]
Awesome, I appreciate your knowledgeable advise on this. Thank you again, I'll close the issue, as thermald is now running smoothly.

Regards
