### ISSUE TITLE
thermald 1.5.3 not respecting specified max_state for intel_powerclamp

### ISSUE THREAD

**Issue by sassmann** [01org/thermal_daemon#99]
Limiting intel_powerclamp to say 20% doesn't work.

thermald --no-daemon --loglevel=info
[...]
 Dumping parsed XML Data
 *** Index 0 ***
Name: GenericX86LaptopDevice
UUID:
type: 0
        Zone 0
         Name: cpu
                 Trip Point 0
                  temp 75000
                  trip type 1
                  hyst id 0
                  sensor type
        Cooling Dev 0
                Type: rapl_controller
                Path:
                Min: 0
                Max: 0
                Step: 1
                AutoDownControl: 0
        Cooling Dev 1
                Type: intel_powerclamp
                Path:
                Min: 0
                Max: 20
                Step: 5
                AutoDownControl: 0
[...]
Set : threshold:73500, temperature:75000, cdev:8(intel_powerclamp), curr_state:5, max_state:50
cdev index:8 consecutive call, increment exponentially state 15
Set : threshold:73500, temperature:76000, cdev:8(intel_powerclamp), curr_state:15, max_state:50
cdev index:8 consecutive call, increment exponentially state 25
Set : threshold:73500, temperature:74000, cdev:8(intel_powerclamp), curr_state:25, max_state:50
Set : threshold:73500, temperature:72000, cdev:8(intel_powerclamp), curr_state:20, max_state:50
Set : threshold:73500, temperature:72000, cdev:8(intel_powerclamp), curr_state:15, max_state:50
Set : threshold:73500, temperature:74000, cdev:8(intel_powerclamp), curr_state:20, max_state:50
cdev index:8 consecutive call, increment exponentially state 30
Set : threshold:73500, temperature:75000, cdev:8(intel_powerclamp), curr_state:30, max_state:50

thermald clearly exceeds the specified max_state of 20

**Comment by pyamsoft** [comment]
In the file `/sys/class/thermald/cooling_device<whatever number powerclamp is>` the actual file max_state shows that it is a read only file. This suggests that the max_state is decided by the system, and is out of the control of thermald.

```
pyamsoft /sys/class/thermal/cooling_device15 $ ls -l
total 0
-rw-r--r-- 1 root root 4.0K Oct 19 18:54 cur_state
-r--r--r-- 1 root root 4.0K Oct 19 18:52 max_state
drwxr-xr-x 2 root root    0 Oct 19 18:53 power
lrwxrwxrwx 1 root root    0 Oct 19 18:52 subsystem -> ../../../../class/thermal
-r--r--r-- 1 root root 4.0K Oct 19 18:52 type
-rw-r--r-- 1 root root 4.0K Oct 19 18:52 uevent
```

**Comment by sassmann** [comment]
Oh, I didn't notice that. Thanks for the info.
